### ISSUE TITLE
依赖少了一个numpy

### ISSUE THREAD

**Issue by sensty** [fengbeibei/get-sep-file#3]

**Comment by fengbeibei** [comment]
没用numpy啊🤣

**Comment by sensty** [comment]
可能是pandas用到了
![image](https://user-images.githubusercontent.com/24983339/93693902-5b7ed300-fb38-11ea-86cb-01d82c5bf5cc.png)

**Comment by fengbeibei** [comment]
对，一般安装pandas都会自动安装numpy的，刚在Mac和Linux下测试是这样的。一般使用conda，基本包里也会有numpy。requirements是自动打包的，所以应该是没问题的
