### ISSUE TITLE
关于lxml版本要求问题

### ISSUE THREAD

**Issue by Daisy-Zhang** [fengbeibei/get-sep-file#5]
不知道windos环境下是否会出现此种情况，但在Mac OS环境下如果lxml版本过高会报错：**bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?** 自己查到并验证的解决方法：降低lxml版本至3.7.0。

**Comment by fengbeibei** [comment]
我是没有安装lxml会报这个错，安装后用的4.5.2没有报错
